# Generated by Django 6.1.2 on 2026-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Bassaddict Sounds KE', max_length=200)),
                ('tagline', models.CharField(default='ADDICTED TO BASS. DRIVEN BY SOUND.', max_length=200)),
                ('phone', models.CharField(default='0794069405', max_length=32)),
                ('whatsapp_number', models.CharField(default='0794069405', max_length=32)),
                ('email', models.EmailField(default='bassaddictsounds@gmail.com', max_length=254)),
                ('address', models.TextField(default='Ground Floor, New Loitoktok House, Luthuli Avenue, Nairobi, Kenya')),
                ('developer_name', models.CharField(default='Sam Gates', max_length=150)),
                ('developer_credit', models.CharField(default='Designed & Developed by Sam Gates — Developer Courtesy', max_length=255)),
                ('developer_email', models.EmailField(blank=True, max_length=254)),
                ('developer_whatsapp', models.CharField(blank=True, max_length=32)),
                ('developer_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business settings',
                'verbose_name_plural': 'business settings',
                'permissions': [('change_developer_attribution', 'Can change developer attribution')],
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='business_settings_singleton', violation_error_message='Only one business settings record is allowed.')],
            },
        ),
    ]
