# Generated by Django 6.1.2 on 2026-10-07 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Owner-entered product attributes. Do not invent specifications.')),
                ('public_price', models.DecimalField(blank=True, decimal_places=2, help_text='Required when the price type is fixed. Leave empty for on-request or contact pricing.', max_digits=12, null=True, verbose_name='public price (KES)')),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('ON_REQUEST', 'On request'), ('CONTACT', 'Contact')], default='FIXED', max_length=20)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('ON_ORDER', 'On order')], default='IN_STOCK', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Private price for this customer. Does not change the public price.', max_digits=12, verbose_name='customer price (KES)')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='catalog.product')),
            ],
            options={
                'verbose_name': 'customer price',
                'verbose_name_plural': 'customer prices',
                'ordering': ['customer__email', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Direct image URL. No upload processing in this phase.', max_length=500, verbose_name='image URL')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark the image that should be shown first.', verbose_name='primary')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('public_price__isnull', True), ('public_price__gte', 0), _connector='OR'), name='product_public_price_non_negative', violation_error_message='Public price cannot be negative.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_type', 'FIXED'), _negated=True), ('public_price__isnull', False), _connector='OR'), name='product_fixed_requires_public_price', violation_error_message='A fixed price product must have a public price.'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='unique_customer_product_price'),
        ),
        migrations.AddConstraint(
            model_name='customerprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='customer_price_non_negative', violation_error_message='Customer price cannot be negative.'),
        ),
    ]
