# Generated by Django 6.1.2 on 2026-10-07 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('PRODUCT', 'Product'), ('INSTALLATION', 'Installation'), ('DELIVERY', 'Delivery'), ('CUSTOM_BUILD', 'Custom build'), ('GENERAL', 'General')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUOTED', 'Quoted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('owner_response', models.TextField(blank=True)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional quote. This does not create a payment.', max_digits=12, null=True, verbose_name='offered price (KES)')),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='delivery fee (KES)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Leave empty for a guest enquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='catalog.product')),
            ],
            options={
                'verbose_name': 'enquiry',
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='enquiry_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='enquiry_quantity_positive', violation_error_message='Quantity must be at least 1.'), models.CheckConstraint(condition=models.Q(('offered_price__isnull', True), ('offered_price__gte', 0), _connector='OR'), name='enquiry_offered_price_non_negative', violation_error_message='Offered price cannot be negative.'), models.CheckConstraint(condition=models.Q(('delivery_fee__isnull', True), ('delivery_fee__gte', 0), _connector='OR'), name='enquiry_delivery_fee_non_negative', violation_error_message='Delivery fee cannot be negative.')],
            },
        ),
    ]
